"""Studio export: enhancement and processing presets as notes (docs/15).

Presets are static dataclasses today, so this export is a snapshot/backup plus a
readable inventory in Obsidian. Notes are regenerated from ``PRESETS`` on every
sync — editing them in Obsidian never changes OmniRip's behavior.
"""

from __future__ import annotations

from dataclasses import asdict, fields, is_dataclass
from pathlib import Path
from typing import Any

from harvester.analysis.enhancement.presets import PRESETS as ENHANCEMENT_PRESETS
from harvester.processing import PRESETS as PROCESSING_PRESETS
from harvester.services.obsidian.frontmatter import encode_frontmatter
from harvester.services.obsidian.naming import studio_note_name
from harvester.services.obsidian.vault import OMNIRIP_NOTE_TYPE, VaultPaths, write_note

_SCALAR_TYPES = (str, int, float, bool)


def _preset_frontmatter(kind: str, preset: Any) -> dict[str, Any]:
    fields_map: dict[str, Any] = {}
    if is_dataclass(preset):
        for field in fields(preset):
            value = getattr(preset, field.name)
            if isinstance(value, _SCALAR_TYPES):
                fields_map[field.name] = value
    return {
        "omnirip": OMNIRIP_NOTE_TYPE,
        "type": "preset",
        "kind": kind,
        "name": getattr(preset, "name", preset.__class__.__name__),
        "description": getattr(preset, "description", ""),
        **fields_map,
        "tags": ["omnirip", "studio"],
    }


def build_preset_note(kind: str, preset_id: str, preset: Any) -> str:
    """Render one preset note from its dataclass."""
    body = (
        f"# {getattr(preset, 'name', preset_id)}\n\n"
        f">{getattr(preset, 'description', '') or 'No description.'}\n\n"
    )
    if is_dataclass(preset):
        for entry in asdict(preset).items():
            key, value = entry
            if key in {"name", "id", "description"}:
                continue
            body += f"- **{key}**: {value}\n"
    return encode_frontmatter(_preset_frontmatter(kind, preset)) + body


def _studio_index() -> str:
    frontmatter = {
        "omnirip": OMNIRIP_NOTE_TYPE,
        "type": "studio-index",
        "tags": ["omnirip", "studio"],
    }
    body = (
        "# Studio — Preset Inventory\n\n"
        "Regenerated by ``OmniRip obsidian-sync``. Editing these notes never affects "
        "OmniRip — they are a readable snapshot of the built-in presets.\n\n"
        "## Enhancement presets\n"
        + "".join(
            f"- [[presets/{studio_note_name(preset_id)}]]\n"
            for preset_id, _ in ENHANCEMENT_PRESETS.items()
        )
        + "\n## Processing presets\n"
        + "".join(
            f"- [[presets/{studio_note_name(preset_id)}]]\n"
            for preset_id, _ in PROCESSING_PRESETS.items()
        )
    )
    return encode_frontmatter(frontmatter) + body


def export_studio(vault: VaultPaths) -> list[Path]:
    """Write all preset notes plus the inventory index, returning the written paths."""
    written: list[Path] = []
    for preset_id, preset in ENHANCEMENT_PRESETS.items():
        path = vault.studio_note(preset_id)
        write_note(path, build_preset_note("enhancement", preset_id, preset))
        written.append(path)
    for preset_id, preset in PROCESSING_PRESETS.items():
        path = vault.studio_note(preset_id)
        write_note(path, build_preset_note("processing", preset_id, preset))
        written.append(path)
    index = vault.root / "Studio" / "README.md"
    write_note(index, _studio_index())
    written.append(index)
    return written


__all__ = ["build_preset_note", "export_studio"]